In [1]:
# import relevant libraries
import numpy as np

In [2]:
array0 = np.array([])

In [3]:
# find the shape of array0
array0.shape

(0,)

In [4]:
array1 = np.array([1, 2, 3, 4, 5])

In [5]:
# find the shape of array1
array1.shape

(5,)

In [6]:
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
# find the shape of array2
array2.shape

(3, 3)

In [8]:
array_zeros = np.zeros((4, 5))

In [9]:
# find the shape of array_zeros
array_zeros.shape

(4, 5)

In [10]:
array_ones = np.ones((3, 6))

In [11]:
# find the shapes of array_ones
array_ones.shape

(3, 6)

In [14]:
array_r0 = np.random.randint(1, 50, 25)
array_r0

array([27, 29, 43, 16, 41,  2, 23, 11,  9, 16, 44, 28, 13, 30, 16, 30, 42,
       16, 40, 41, 44, 41,  2,  3, 40])

In [15]:
# find the share of array_r0
array_r0.shape

(25,)

In [16]:
# reshape array_r0
# to create a new multi-dimentional numpy array
# containing array_r0's items with 5 rows & 5 columns
array_r0.reshape((5, 5))

array([[27, 29, 43, 16, 41],
       [ 2, 23, 11,  9, 16],
       [44, 28, 13, 30, 16],
       [30, 42, 16, 40, 41],
       [44, 41,  2,  3, 40]])

In [17]:
# note that array_r0 itesef was not modified
array_r0

array([27, 29, 43, 16, 41,  2, 23, 11,  9, 16, 44, 28, 13, 30, 16, 30, 42,
       16, 40, 41, 44, 41,  2,  3, 40])

In [18]:
array_r1 = np.random.randint(1, 50, 20)
array_r1

array([36, 11, 36, 44, 30, 29,  6, 22, 48, 34, 29, 22, 20, 45, 41,  2, 45,
       43, 39, 31])

In [19]:
# find the share of array_r1
array_r1.shape

(20,)

In [20]:
# reshape array_r1
# to create a new multi-dimentional numpy array
# containing array_r1's items with 10 rows & 2 columns
array_r1.reshape((10, 2))

array([[36, 11],
       [36, 44],
       [30, 29],
       [ 6, 22],
       [48, 34],
       [29, 22],
       [20, 45],
       [41,  2],
       [45, 43],
       [39, 31]])

In [21]:
# reshape array_r1
# to create a new multi-dimentional numpy array
# containing array_r1's items with 2 rows & 10 columns
array_r1.reshape((2, 10))

array([[36, 11, 36, 44, 30, 29,  6, 22, 48, 34],
       [29, 22, 20, 45, 41,  2, 45, 43, 39, 31]])

In [22]:
# reshape array_r1
# to create a new multi-dimentional numpy array
# containing array_r1's items with 4 rows & 5 columns
array_r1.reshape((4, 5))

array([[36, 11, 36, 44, 30],
       [29,  6, 22, 48, 34],
       [29, 22, 20, 45, 41],
       [ 2, 45, 43, 39, 31]])

In [23]:
# reshape array_r1
# to create a new multi-dimentional numpy array
# containing array_r1's items with 5 rows & 4 columns
array_r1.reshape((5, 4))

array([[36, 11, 36, 44],
       [30, 29,  6, 22],
       [48, 34, 29, 22],
       [20, 45, 41,  2],
       [45, 43, 39, 31]])

In [24]:
# note that array_r1 itself was not modified
array_r1

array([36, 11, 36, 44, 30, 29,  6, 22, 48, 34, 29, 22, 20, 45, 41,  2, 45,
       43, 39, 31])

In [25]:
array_r2 = np.random.randint(1, 50, (4, 4))
array_r2

array([[49,  9, 17, 38],
       [40, 42,  5, 40],
       [31, 19,  1, 19],
       [22, 27, 44, 44]])

In [26]:
# find the share of array_r2
array_r2.shape

(4, 4)

In [27]:
# reshape array_r2
# to create a new one-dimentional numpy array containg array_r2's items
# with length 16
array_r2.reshape(16)

array([49,  9, 17, 38, 40, 42,  5, 40, 31, 19,  1, 19, 22, 27, 44, 44])

In [28]:
# note that array_r2 itself was not modified
array_r2

array([[49,  9, 17, 38],
       [40, 42,  5, 40],
       [31, 19,  1, 19],
       [22, 27, 44, 44]])